org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

parchment_minecraft_version=1.21.8
parchment_mappings_version=2025.09.14

minecraft_version=1.21.8
minecraft_version_range=[1.21.8,1.22)
neo_version=21.8.53
neo_version_range=[21,)
loader_version_range=[4,)

mod_id=entity_information
mod_name=EntityInformation
mod_license=All Rights Reserved
mod_version=1.0
mod_group_id=org.hhoa.mc
mod_authors=hhoa
mod_description=Provide item information and biological map
